languageCode = "en"
languageName = "English"
weight = 1
title = "Claudia Montanaro"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "hellouw!"

[params.author]
  name = "Claudia Montanaro"
  email = "c.montanaro@uva.nl"
  headline = "PhD student | University of Amsterdam"
  bio = "I study the semiotic implications of things that mean other things. My current project investigates whether laundry instructions constitute a form of oppressive discourse. I have opinions about Derrida that I will share with you whether you asked or not."
  links = [
    { github = "https://github.com/yourusername" },
    { email = "mailto:c.montanaro@uva.nl" },
  ]
  image = "img/itsme.png"